---
title: "Chapter 1 - Getting Started"
author: "Greg Foletta"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
    toc: true
---


```{r setup, include=FALSE}
library(tidyverse)
library(magrittr)
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
```

# What Can Be Forecast?

Forecasting is required in many situations, and the forecasts can be years in advance, or only a few minutes.

Some things are easier to forecast than others - take the time of tomorrow's sunrise versus tomorrow's lotto numbers. The predictability depends on several factors including:

1. How well we understand the factors that contribute to it.
1. How much data is available.
1. Whether the forecasts can affect the thing we are trtying to forecast.

# Forecasting, Planning and Goals

Forecasting is frequently confused with *planning* and *goals*:

**Forecasting** is about predicting the future as accurately as possible, given all information available. This includes historical data and knowledge of events in the future that may impact the forecasts.

**Goals** are what you would like to have happen. Goals should be linked to forecasts and plans, but this does not always occur. Too often they are set without any plan to reach them, and no forecasts to determine whether they are realistic.

**Planning** is a response to forecasts and goals. It involves determining the appropriate actions that are required to make your forecasts match your goals.


Forecasting is an integral part of the decision-making activities of management. 

- **Short-term** forecasts for scheduling of personnel, production, and transportation.
- **Medium-term** forecasts to determine future resource requirements in order to purchase raw materials, hire personnel, or buy machinery and equipment.
- **Long-term** forecasts for strategic planning.


# Determining What To Forecast

Consider a manufacturing environment, the questions are whether forecasts are needed:

- For every product line, or for groups of products?
- Every sales outluet, for outlets grouped by region, or only for total sales?
- Weekly, monthly, or annual data?

The forecasting horizon also needs to be determined: one month, six months, ten years? Different types of models are necessary depending on this horizon.

It's worth spending time talking to the people who will use the forecasts to ensure you meet their needs, and how the forecasts are to be used.

It will then be necessary to find or collect the data on which the forecasts will be based. It may already exist, and the majority of time may be spent trying to find where the data is located.

# Forecasting Data and Methods

If there are no data available, **qualitative forecasting** methods must be used. These methods are not guesswork: they are well-developed structured approached to obtaining good forecasts using historical data.

**Quantitative forecasting** can be applied when two conditions are satisfied:

- Numerical information about the past is available.
- It is reasonable to assume that some aspects of past patters will continue into the future.

Most quantitative predictions problems either use:

1. Time series data, collected at regular intervals over time, or
1. Cross-sectional data, collected at a single point in time.

## Time Series Forecasting

Anything observed sequentially over time is a time series. The observations can be at regular or irregular intervals.

When forecasting time series data, the aim is to estimate how the sequence of observations will continue into the future.

The simplest time series forecasting methods use only information on the varaible to be forecast, and make no attempt to discover the factors that affect its behaviour. They extrapolat seasonal patterns, but ignore all other information such as marketing initiatives, competitor activity, changes in economic conditions, etc.

# Predictor Variables

A model of electricity demand with predictor variables might be of the form:

$$ ED = f(current temp, strength of economy, population, time of day, day of week, \epsilon $$ 

This is an **explanitory model**. We could also use a time series model for forecasting. In this case:

$$ ED_{t+1} = f(ED_t, ED_{t-1}, ED_{t-2}, \ldots, \epsilon) $$

There is also a third type of model which combines the features of the above two models:

$$ ED_{t+1} = f(ED_t, current, time, day, \epsilon) $$

These types of "mixed models" have various names: dynamic regression, panel data, longitudinal models, transfer function models, and linear system models (assuming $f()$ is linear).

An explanitory model is useful because it incorporates information about other variables, rather than only historical values. However there are reasons a time series model may be selected:

- System is not well understood.
- System is understood, but it's difficult to measure the relationships that are assumed to govern its behaviour.
- Difficult to know or forecast the future values of the various predictors
- May only be concerned with what will happen, not why it happens.

# Basic Steps

A forecasting task usually involves five basic steps:

## Problem Definition

Often the most difficult step, defining the problem carefully requires an understanding of the way the forecasts will be used, who will use them, and how the forecasting function fits within the organisation. A forecaster needs to spend time talking to everyone who will be involved in collecting data, maintaining databases, and using the forecasts.

## Gathering Information

There are two types of data required:

- Statistical data
- Accumulated expertise of the people who collect the data.

Often it's difficult to obtain historical data, in which case judgemental forecasting methods can be used. Occasionally old data will be less useful due to structural changes in the system being forecast, so the most recent data may be chosen.

However good statistical models will handle evolutionary changes in the system - don't throw away good data unnecessarily.

## Preliminary (Exploratory) Analysis

Start by graphing the data - are there consistent patterns? Is there a significant trend? Is seasonality important? Are there business cycles? Are there outliers?

## Choosing and Fitting Models

The best model to use depends on the availability of historical data, the strength of relationships between the forecast and explanitory variables, and the way in which the forecasts are to be used.

Each model is an artificial construct based on a set of assumptions. Models include regression models, exponential smoothing methods, Box-Jenkins ARIMA models, dynamic regression models, and hierarchical forecasting.

## Using and Evaluating a Forecasting Model

The performance of a model can only be properly evaluated after the data for the forecast period has become available. There are also organisational issues in using and acting on the forecasts.

Other practical issues include handling missing values and outliers, or dealing with short time series.

# Statistical Forecasting Perspective

The thing we're trying to forecast is unknown, and can be thought of as a random variable. In most forecasting scenarios, the variation of the thing we are trying to forecast shrinks as the event approaches. The further ahead we forecast, the more uncertain we are.

When we obtain a forecast, we are estimating the middle of a range of possible values. This is accompanied by a **prediction interval** giving a range of values, for example a 95% prediction interval. The average line of all possible future values is caled the **point forecasts**.

Subscript $t$ is time, and $y_t$ denotes an observation at time $t$. If we denote all the information observed as $\mathcal{I}$ and want to forecast $y_t$, we write $y_t|\mathcal{I}$. This means "the random variable $y_t$ given we know $\mathcal{I}$.

The set of values that this random variable could take, along with their relative probabilities is known as the probability distribution of $y_t|\mathcal{I}$. In forecasting we call this the **forecast distribution**.

When talking about a forecast of $y_t$, it is denoted as $\hat{y}_t$.

$\hat{y}_{t|t-1}$ means the forecast of $y_t$ taking into account all previous observations $(y_1, \ldots, y_{t-1})$.

$\hat{y}_{T+h|T}$ means the forecast of $y_{T+h}$ taking into account $(y_1, \ldots, y_T}$. I.e. an h-step forecast taking account of all observations up to time $T$.