---
title: "Forecasting - Principles and Practice"
author: "Greg Foletta"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
    toc: true
---

# Chapter 1 - Getting Started

* [Notes](01-getting_started.html) - Planning & Goals, Basic Steps, Choosing and Fitting Models.

# Chapter 2 - Time Series Graphics

* [Notes & Exercises](02-time_series_graphics.html) - `tsibble` objects, Time Plots, Scatterplots, Lag Plots, Autocorrelation.

# Chapter 3 - Time Series Decomposition

* [Notes & Exercises](03-time_series_decomposition.html) - Transformations and Adjustments, Time Series Components, Moving Averages, Classical Decomposition; X11, SEATS and STL Decomposition

# Chapter 4 - Time Series Features

* [Notes & Exercises](04-time_series_features.html) - Simple Features, ACF Features, STL Features.

# Chapter 5 - The Forecaster's Toolbox

* [Notes](05-forecasters_toolbox.html) - Simple Methods, Fitted Values and Residuals, Residual Diagnostics, Forecast Distributions, Forecasting Using Transformations & Decompositions, Evaluating Forecast Accuracy
* [Exercises](05-exercises.html)

# Chapter 6 - Judgmental Forecasts

* [Notes](06-judgemental_forecasts.html) - Limitations, Principles, Delphi Method, Scenario Forecasting, Judgemental Adjustments.

# Chapter 7 - Time Series Regression Models 

* [Notes](07-time_series_regression.html) - Linear, Least Squares, Selecting Predictors, Forecasting with Regression, Martix Formulation, Non-linear Regression.
* [Exercises](07-exercises.html)

# Chapter 8 - Exponential Smoothing

* [Notes](08-exponential_smoothing.html) - Simple exponential smoothing, Holt's Method, Holt-Winters Seasonal Method, Innovations State Space Models.
* [Exercises](08-exercises.html) 

